import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TodoProvider } from "./context/todoContext";
import Header from "./components/header";
import SidebarMenu from "./components/sidebar";
import { CategoryProvider } from "./context/categoryCotext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TodoProvider>
          <CategoryProvider>
            <div className=" flex flex-1 overflow-hidden select-none">
              {/* Sidebar */}
              <SidebarMenu />

              <div className=" flex-1 bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-gray-100">
                <Header />
                {children}
              </div>
            </div>
          </CategoryProvider>
        </TodoProvider>
      </body>
    </html>
  );
}
